package model.Units;

public enum NonCivilianUnitType {
    Archer("Arc"),
    ChariotArcher("CAr"),
    Scout("Sco"),
    Spearman("Spm"),
    Warrior("War"),
    BALLISTA("Bal"),
    CAMEL_ARCHER("CmA"),
    CATAPULT("Cat"),
    CHO_KO_NU("CKN"),
    COMPANION_CAVALRY("CCa"),
    CROSSBOWMAN("Crm"),
    HORSEMAN("Hom"),
    KNIGHT("Kni"),
    LANDSKNECHT("LSk"),
    LEGION("Leg"),
    LONGBOW_MAN("LBM"),
    LONG_SWORDS_MAN("LSM"),
    MANDEKALU_CAVALRY("MCA"),
    MOHAWS_WARRIOR("MWa"),
    NARESUANS_ELEPHANT("NEl"),
    PIKEMAN("Pim"),
    SAMURAI("Sam"),
    SWORDSMAN("Swm"),
    TREBUCHET("Trb"),
    ANTI_AIRCRAFT_GUN("AAG"),
    ANTI_TANK_GUN("ATG"),
    ARTILLERY("Art"),
    BATTLESHIP("Bas"),
    CARRIER("Car"),
    DESTROYER("Des"),
    FIGHTER("Fig"),
    FOREIGN_LEGION("FLe"),
    INFANTRY("Inf"),
    IRONCLAD("IrC"),
    PANZER("Pan"),
    SUBMARINER("Sub"),
    TANK("Tan"),
    ZERO("Zer"),
    CANON("Can"),
    CARAVEL("Crv"),
    CAVALRY("Cav"),
    COSSACK("Cos"),
    FRIGATE("Frg"),
    JANISSARY("Jan"),
    LANCER("Lan"),
    MINUTEMAN("Mim"),
    MUSKETEER("Mus"),
    MUSKETMAN("Msm"),
    RIFLEMAN("Rim"),
    SHIP_OF_THE_LINE("Sol"),
    SIAPHI("Sia");
    public final String icon;
    NonCivilianUnitType(String icon){
        this.icon = icon;
    }
}